CREATE TABLE categoria
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    preco_diaria DECIMAL(10, 2)                          NOT NULL,
    capacidade   INT                                     NOT NULL
);

CREATE TABLE comodidade
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nome VARCHAR(100)                            NOT NULL
);

CREATE TABLE servico_adicional
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nome_servico VARCHAR(100)                            NOT NULL,
    descricao    TEXT,
    preco        DECIMAL(10, 2)                          NOT NULL
);

CREATE TABLE cliente
(
    cpf             CHAR(11) PRIMARY KEY, -- CPF é Char(11) fixo
    nome            VARCHAR(150) NOT NULL,
    data_nascimento DATE         NOT NULL,
    email           VARCHAR(150) NOT NULL,
    telefone        VARCHAR(20)           -- Opcional ou NOT NULL, você decide
);

CREATE TABLE hotel
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nome VARCHAR(150)                            NOT NULL
);

CREATE TABLE endereco
(
    hotel_id BIGINT PRIMARY KEY,
    cep      VARCHAR(10),
    rua      VARCHAR(150),
    numero   VARCHAR(20),
    bairro   VARCHAR(100),
    cidade   VARCHAR(100),
    estado   CHAR(2),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE
);

CREATE TABLE email_hotel
(
    hotel_id BIGINT,
    email    VARCHAR(150),
    PRIMARY KEY (hotel_id, email),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE
);

CREATE TABLE telefone_hotel
(
    hotel_id BIGINT,
    telefone VARCHAR(20),
    PRIMARY KEY (hotel_id, telefone),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE
);

CREATE TABLE quarto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    hotel_id     BIGINT                                  NOT NULL,
    categoria_id BIGINT                                  NOT NULL,
    numero       VARCHAR(10)                             NOT NULL,
    status       VARCHAR(20) DEFAULT 'Disponível', -- Ex: Disponível, Ocupado, Manutenção
    area         DECIMAL(10, 2),                   -- Em metros quadrados
    FOREIGN KEY (hotel_id) REFERENCES hotel (id),
    FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE TABLE quarto_comodidade
(
    quarto_id     BIGINT,
    comodidade_id BIGINT,
    PRIMARY KEY (quarto_id, comodidade_id),
    FOREIGN KEY (quarto_id) REFERENCES quarto (id),
    FOREIGN KEY (comodidade_id) REFERENCES comodidade (id)
);

CREATE TABLE funcionario
(
    cpf      CHAR(11) PRIMARY KEY,
    hotel_id BIGINT       NOT NULL,
    nome     VARCHAR(150) NOT NULL,
    email    VARCHAR(150) NOT NULL,
    cargo    VARCHAR(50),
    salario  DECIMAL(10, 2),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id)
);

CREATE TABLE reserva
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    quarto_id              BIGINT      NOT NULL,
    cpf_cliente            CHAR(11) NOT NULL,
    data_reserva  TIMESTAMPTZ NOT NULL DEFAULT now(), -- Preenche data atual sozinho
    data_checkin_previsto  DATE     NOT NULL,
    data_checkout_previsto DATE     NOT NULL,
    status_reserva         VARCHAR(20) DEFAULT 'Pendente',
    FOREIGN KEY (quarto_id) REFERENCES quarto (id),
    FOREIGN KEY (cpf_cliente) REFERENCES cliente (cpf),
    CONSTRAINT chk_status_reserva CHECK (status_reserva IN ('Pendente', 'Confirmada', 'Cancelada', 'Concluída'))
);

CREATE TABLE reserva_servico
(
    reserva_id           BIGINT,
    servico_adicional_id BIGINT,
    quantidade           BIGINT DEFAULT 1,
    PRIMARY KEY (reserva_id, servico_adicional_id),
    FOREIGN KEY (reserva_id) REFERENCES reserva (id),
    FOREIGN KEY (servico_adicional_id) REFERENCES servico_adicional (id),
    CONSTRAINT chk_quantidade CHECK (quantidade > 0)
);

CREATE TABLE hospedagem
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    reserva_id         BIGINT, -- Aceita NULL (Walk-in)
    quarto_id          BIGINT      NOT NULL,
    cpf_cliente        CHAR(11) NOT NULL,
    data_checkin_real  TIMESTAMPTZ NOT NULL DEFAULT now(),
    data_checkout_real TIMESTAMPTZ,
    FOREIGN KEY (reserva_id) REFERENCES reserva (id),
    FOREIGN KEY (quarto_id) REFERENCES quarto (id),
    FOREIGN KEY (cpf_cliente) REFERENCES cliente (cpf),
    CONSTRAINT unq_reserva_hospedagem UNIQUE (reserva_id)
);

CREATE TABLE pagamento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    hospedagem_id    BIGINT, -- NULL se for sinal de reserva
    reserva_id       BIGINT, -- NULL se for walk-in
    valor_total      DECIMAL(10, 2) NOT NULL,
    data_pagamento   TIMESTAMPTZ NOT NULL DEFAULT now(),
    metodo_pagamento VARCHAR(50)    NOT NULL,
    status_pagamento VARCHAR(20) DEFAULT 'Pendente',
    FOREIGN KEY (hospedagem_id) REFERENCES hospedagem (id),
    FOREIGN KEY (reserva_id) REFERENCES reserva (id),
    CONSTRAINT chk_status_pgto CHECK (status_pagamento IN ('Pendente', 'Concluído', 'Estornado')),
    CONSTRAINT chk_metodo_pgto CHECK (metodo_pagamento IN ('Dinheiro', 'Cartão Crédito', 'Cartão Débito', 'Pix')),
    CONSTRAINT ck_pagamento_origem CHECK (
        (hospedagem_id IS NOT NULL AND reserva_id IS NULL)
        OR
        (hospedagem_id IS NULL AND reserva_id IS NOT NULL)
        )

);
