CREATE TABLE categoria
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    preco_diaria DECIMAL(10, 2)                          NOT NULL,
    capacidade   INT                                     NOT NULL,
    CONSTRAINT chk_preco_diaria CHECK (preco_diaria >= 0),
    CONSTRAINT chk_capacidade CHECK (capacidade > 0)
);

CREATE TABLE comodidade
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nome VARCHAR(100)                            NOT NULL
);

CREATE TABLE servico_adicional
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nome_servico VARCHAR(100)                            NOT NULL,
    descricao    TEXT,
    preco        DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT chk_preco_servico CHECK (preco >= 0)
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(30) NOT NULL
);

CREATE TABLE cliente
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    cpf             CHAR(11) NOT NULL UNIQUE,
    nome            VARCHAR(150) NOT NULL,
    data_nascimento DATE         NOT NULL,
    telefone        VARCHAR(20),
    CONSTRAINT fk_cliente_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE hotel
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nome VARCHAR(255)                            NOT NULL,
    cnpj VARCHAR(14)                             NOT NULL UNIQUE
);

CREATE TABLE endereco
(
    hotel_id BIGINT PRIMARY KEY,
    cep      VARCHAR(10),
    rua      VARCHAR(150),
    numero   VARCHAR(20),
    bairro   VARCHAR(100),
    cidade   VARCHAR(100),
    estado   CHAR(2),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE
);

CREATE TABLE email_hotel
(
    hotel_id BIGINT NOT NULL,
    email    VARCHAR(150) NOT NULL,
    PRIMARY KEY (hotel_id, email),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE
);

CREATE TABLE telefone_hotel
(
    hotel_id BIGINT NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    PRIMARY KEY (hotel_id, telefone),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE
);

CREATE TABLE funcionario
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    cpf      CHAR(11) NOT NULL UNIQUE,
    hotel_id BIGINT       NOT NULL,
    nome     VARCHAR(150) NOT NULL,
    cargo    VARCHAR(100),
    salario  DECIMAL(10, 2),
    CONSTRAINT fk_funcionario_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_funcionario_hotel
        FOREIGN KEY (hotel_id) REFERENCES hotel (id),
    CONSTRAINT chk_salario CHECK (salario >= 0)
);

CREATE TABLE quarto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    hotel_id     BIGINT                                  NOT NULL,
    categoria_id BIGINT                                  NOT NULL,
    numero       VARCHAR(10)                             NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL',
    area         DECIMAL(10, 2),                   
    FOREIGN KEY (hotel_id) REFERENCES hotel (id),
    FOREIGN KEY (categoria_id) REFERENCES categoria (id),
    CONSTRAINT chk_status_quarto CHECK (status IN ('DISPONIVEL','OCUPADO','MANUTENCAO','LIMPEZA')),
    CONSTRAINT chk_area_quarto CHECK (area > 0),
    CONSTRAINT unq_quarto_hotel_numero UNIQUE (hotel_id, numero)
);

CREATE TABLE quarto_comodidade
(
    quarto_id     BIGINT NOT NULL,
    comodidade_id BIGINT NOT NULL,
    PRIMARY KEY (quarto_id, comodidade_id),
    FOREIGN KEY (quarto_id) REFERENCES quarto (id) ON DELETE CASCADE,
    FOREIGN KEY (comodidade_id) REFERENCES comodidade (id) ON DELETE CASCADE
);

CREATE TABLE reserva
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    data_reserva           TIMESTAMPTZ NOT NULL DEFAULT now(),
    data_checkin_previsto  DATE     NOT NULL,
    data_checkout_previsto DATE     NOT NULL,
    status_reserva         VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT chk_status_reserva CHECK (status_reserva IN ('PENDENTE','CONFIRMADA','CANCELADA','CONCLUIDA')),
    CONSTRAINT chk_datas_reserva CHECK (data_checkin_previsto < data_checkout_previsto)
);

CREATE TABLE reserva_quarto
(
    reserva_id BIGINT NOT NULL,
    quarto_id  BIGINT NOT NULL,
    PRIMARY KEY (reserva_id, quarto_id),
    FOREIGN KEY (reserva_id) REFERENCES reserva (id) ON DELETE CASCADE,
    FOREIGN KEY (quarto_id) REFERENCES quarto (id)
);

CREATE TABLE reserva_servico
(
    reserva_id           BIGINT NOT NULL,
    servico_adicional_id BIGINT NOT NULL,
    quantidade           BIGINT DEFAULT 1,
    PRIMARY KEY (reserva_id, servico_adicional_id),
    FOREIGN KEY (reserva_id) REFERENCES reserva (id) ON DELETE CASCADE,
    FOREIGN KEY (servico_adicional_id) REFERENCES servico_adicional (id),
    CONSTRAINT chk_quantidade CHECK (quantidade > 0)
);

CREATE TABLE hospedagem
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    reserva_id BIGINT UNIQUE,
    cliente_id BIGINT NOT NULL,
    data_checkin_real  TIMESTAMPTZ NOT NULL DEFAULT now(),
    data_checkout_real TIMESTAMPTZ,
    CONSTRAINT fk_hospedagem_reserva
        FOREIGN KEY (reserva_id) REFERENCES reserva (id),
    CONSTRAINT fk_hospedagem_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE hospedagem_quarto
(
    hospedagem_id BIGINT NOT NULL,
    quarto_id     BIGINT NOT NULL,
    PRIMARY KEY (hospedagem_id, quarto_id),
    FOREIGN KEY (hospedagem_id) REFERENCES hospedagem (id) ON DELETE CASCADE,
    FOREIGN KEY (quarto_id) REFERENCES quarto (id)
);

CREATE TABLE hospedagem_servico
(
    hospedagem_id        BIGINT NOT NULL,
    servico_adicional_id BIGINT NOT NULL,
    quantidade           BIGINT DEFAULT 1,
    data_solicitacao     TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (hospedagem_id, servico_adicional_id, data_solicitacao),
    FOREIGN KEY (hospedagem_id) REFERENCES hospedagem (id),
    FOREIGN KEY (servico_adicional_id) REFERENCES servico_adicional (id),
    CONSTRAINT chk_hs_quantidade CHECK (quantidade > 0)
);

CREATE TABLE pagamento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    hospedagem_id    BIGINT,
    reserva_id       BIGINT,
    valor_total      DECIMAL(10, 2) NOT NULL,
    data_pagamento   TIMESTAMPTZ NOT NULL DEFAULT now(),
    metodo_pagamento VARCHAR(50) NOT NULL,
    status_pagamento VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    FOREIGN KEY (hospedagem_id) REFERENCES hospedagem (id),
    FOREIGN KEY (reserva_id) REFERENCES reserva (id),
    CONSTRAINT chk_status_pgto CHECK (
        status_pagamento IN ('PENDENTE', 'CONCLUIDO', 'ESTORNADO')
        ),
    CONSTRAINT chk_metodo_pgto CHECK (
        metodo_pagamento IN ('DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX')
        ),
    CONSTRAINT ck_pagamento_origem CHECK (
        (hospedagem_id IS NOT NULL AND reserva_id IS NULL)
            OR
        (hospedagem_id IS NULL AND reserva_id IS NOT NULL)
        )
);
